/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.yann.servlet.rssviewer;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

import com.thoughtworks.xstream.XStream;

import br.com.yann.servlet.rssviewer.model.Note;

public class RssViewers {
    

    public static void main(String[] args) throws IOException, InterruptedException {
     HttpClient client = HttpClient.newHttpClient();
     HttpRequest request = HttpRequest.newBuilder().uri(URI.create("https://www.w3schools.com/xml/note.xml")).build();
     
     HttpResponse<String> send = client.send(request, HttpResponse.BodyHandlers.ofString());
     String xml = send.body();
     XStream stream = new XStream(); 
     stream.alias("Note", Note.class);
     Note note = (Note) stream.fromXML(xml);
     System.out.println(note);

    }
}
