/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mindful.Quote;

import java.io.IOException;
import Mindful.Quote.Data.JsonManager;
import Mindful.Quote.Model.Quote;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;


@SpringBootApplication
@RestController
public class App {
 
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);    

    }

    @GetMapping("/hello")
    public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
        return String.format("Hello %s!", name);
    }

    @GetMapping("/sum")
    public double sum(@RequestParam(value = "value1", defaultValue = "0.0") double value1, 
                      @RequestParam(value = "value2", defaultValue = "0.0") double value2) {
        return value1 + value2;
    }

    @GetMapping("/quote")
    public String Quote(){
        try {
            JsonManager jsonManager = new JsonManager();
            Quote firstQuote = (Quote) jsonManager.getQuotes().toArray()[(int) (Math.random()*jsonManager.getTotal())];
            return String.format("%s by %s", firstQuote.quote, firstQuote.author);
        } catch (IOException e) {
            return String.format("%s",e);
        }
      
    }
}
