/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.yann.servlet.rssviewer;

// import org.junit.Test;
// import static org.junit.Assert.*;

// public class AppTest {
//     @Test public void appHasAGreeting() {
//         RssViewers classUnderTest = new RssViewers();
//         assertNotNull("app should have a greeting", classUnderTest.getGreeting());
// //     }
// }
